/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zakazanipregledi;

import domen.Karton;
import domen.Lekar;
import domen.ZakazaniPregled;
import forme.FormMode;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import kontroler.Kontroler;
import modeli.ZakazaniPregledTabelaModel;
import transfer.ServerskiOdgovor;
import util.ResponseStatus;

/**
 *
 * @author Danilo
 */
public class PretragaZakazanihPregledaForma extends javax.swing.JFrame {

    /**
     * Creates new form PretragaZakazanihPregledaForma
     */
    public PretragaZakazanihPregledaForma() {
        initComponents();
        centriraj();
        postaviNepromenljivostDimenzija();
        srediTabelu();
        srediDugmice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretragaZakazanihPregleda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZakazaniPregledi = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnPrikaziZakazaniPregled = new javax.swing.JButton();
        btnObrisiZakazaniPregled = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga zakazanih pregleda");

        jLabel1.setText("Pretraži zakazani pregled po imenu,  prezimenu ili broju knjižice pacijenta:");

        txtPretragaZakazanihPregleda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaZakazanihPregledaKeyReleased(evt);
            }
        });

        tabelaZakazaniPregledi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaZakazaniPregledi);

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnPrikaziZakazaniPregled.setText("Prikaži zakazani pregled");
        btnPrikaziZakazaniPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziZakazaniPregledActionPerformed(evt);
            }
        });

        btnObrisiZakazaniPregled.setText("Obriši zakazani pregled");
        btnObrisiZakazaniPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZakazaniPregledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretragaZakazanihPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPretrazi))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPrikaziZakazaniPregled)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisiZakazaniPregled)))
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretragaZakazanihPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPretrazi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikaziZakazaniPregled)
                    .addComponent(btnObrisiZakazaniPregled))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        pretraga();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void txtPretragaZakazanihPregledaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaZakazanihPregledaKeyReleased
        pretraga();
    }//GEN-LAST:event_txtPretragaZakazanihPregledaKeyReleased

    private void btnPrikaziZakazaniPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziZakazaniPregledActionPerformed
        int red = tabelaZakazaniPregledi.getSelectedRow();
        if(red==-1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan red!","Greška",JOptionPane.ERROR_MESSAGE);
            return;
        }
        FormMode formMode;
        if(Kontroler.getInstanca().getUlogovani() instanceof Lekar){
            formMode = FormMode.FORM_VIEW;
        }
        else{
            formMode = FormMode.FORM_UPDATE;
        }
        ZakazaniPregledTabelaModel ztm = (ZakazaniPregledTabelaModel) tabelaZakazaniPregledi.getModel();
        ZakazaniPregled zp = ztm.vratiZakazaniPregled(red);
        ZakazivanjePregledaForma zpf = new ZakazivanjePregledaForma(this, true, formMode, zp);
        zpf.setVisible(true);       
    }//GEN-LAST:event_btnPrikaziZakazaniPregledActionPerformed

    private void btnObrisiZakazaniPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZakazaniPregledActionPerformed
        int red = tabelaZakazaniPregledi.getSelectedRow();
        if(red==-1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan red!","Greška",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete zakazani pregled?");
        if(odgovor==JOptionPane.OK_OPTION){
            ZakazaniPregledTabelaModel ztm = (ZakazaniPregledTabelaModel) tabelaZakazaniPregledi.getModel();
            ZakazaniPregled zp = ztm.vratiZakazaniPregled(red);
            ServerskiOdgovor so = Kontroler.getInstanca().obrisiZakazaniPregled(zp);
            if(so.getResponseStatus()==ResponseStatus.ERROR){
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, so.getPoruka(),"Poruka",JOptionPane.INFORMATION_MESSAGE);
                pretraga();
            }
        }
            
            }//GEN-LAST:event_btnObrisiZakazaniPregledActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaZakazanihPregledaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaZakazanihPregledaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaZakazanihPregledaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaZakazanihPregledaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaZakazanihPregledaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisiZakazaniPregled;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziZakazaniPregled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaZakazaniPregledi;
    private javax.swing.JTextField txtPretragaZakazanihPregleda;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ZakazaniPregledTabelaModel ztm = new ZakazaniPregledTabelaModel();
        tabelaZakazaniPregledi.setModel(ztm);
        pretraga();
        
    }

    public void pretraga() {
        String vrednost = txtPretragaZakazanihPregleda.getText();
        ZakazaniPregledTabelaModel ztm = (ZakazaniPregledTabelaModel) tabelaZakazaniPregledi.getModel();
        ZakazaniPregled zp = new ZakazaniPregled();
        Karton k = new Karton();
        k.setBrojKnjizice(vrednost);
        k.setIme(vrednost);
        k.setPrezime(vrednost);
        zp.setKarton(k);
        List<ZakazaniPregled> pregledi = Kontroler.getInstanca().vratiListuZakazanihPregleda(zp);
        ztm.setPregledi(pregledi);
    }

    private void srediDugmice() {
        if(Kontroler.getInstanca().getUlogovani() instanceof Lekar){
            btnObrisiZakazaniPregled.setVisible(false);
        }
    }

    private void centriraj() {
        setLocationRelativeTo(null);
    }

    private void postaviNepromenljivostDimenzija() {
        setResizable(false);
    }
}
