/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kartoni;

import domen.Karton;
import domen.Lekar;
import forme.FormMode;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.KartonTabelaModel;
import transfer.ServerskiOdgovor;
import util.ResponseStatus;

/**
 *
 * @author Danilo
 */
public class PretragaKartonaForma extends javax.swing.JFrame {

    /**
     * Creates new form PretragaKartonaForma
     */
    public PretragaKartonaForma() {
        initComponents();
        centriraj();
        postaviDugmice();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImePrezimeLbo = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaKartoni = new javax.swing.JTable();
        btnPrikaziKarton = new javax.swing.JButton();
        jButtonDeaktiviraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga kartona");
        setResizable(false);

        jLabel1.setText("Pretraži karton po imenu, prezimenu ili LBO pacijenta:");

        txtImePrezimeLbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImePrezimeLboActionPerformed(evt);
            }
        });
        txtImePrezimeLbo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImePrezimeLboKeyReleased(evt);
            }
        });

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tabelaKartoni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaKartoni);

        btnPrikaziKarton.setText("Prikaži karton");
        btnPrikaziKarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziKartonActionPerformed(evt);
            }
        });

        jButtonDeaktiviraj.setText("Deaktiviraj karton");
        jButtonDeaktiviraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeaktivirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtImePrezimeLbo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPretrazi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrikaziKarton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDeaktiviraj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImePrezimeLbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPretrazi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikaziKarton)
                    .addComponent(jButtonDeaktiviraj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        pretraga();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void txtImePrezimeLboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImePrezimeLboActionPerformed
        
    }//GEN-LAST:event_txtImePrezimeLboActionPerformed

    private void txtImePrezimeLboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImePrezimeLboKeyReleased
        
    }//GEN-LAST:event_txtImePrezimeLboKeyReleased

    private void btnPrikaziKartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziKartonActionPerformed
        int red = tabelaKartoni.getSelectedRow();
        if(red==-1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan red!","Greška",JOptionPane.ERROR_MESSAGE);
            return;
        }
        FormMode formMode;
        if(Kontroler.getInstanca().getUlogovani() instanceof Lekar){
            formMode = FormMode.FORM_VIEW;
        }
        else{
            formMode = FormMode.FORM_UPDATE;
        }
        KartonTabelaModel ktm = (KartonTabelaModel) tabelaKartoni.getModel();
        Karton k = ktm.vratiKarton(red);
        DodavanjeKartonaForma dkf = new DodavanjeKartonaForma(this, true, formMode, k);
        dkf.setVisible(true);
    }//GEN-LAST:event_btnPrikaziKartonActionPerformed

    private void jButtonDeaktivirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeaktivirajActionPerformed
        int red = tabelaKartoni.getSelectedRow();
        if(red==-1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan red!","Greška",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete karton?");
        if(odgovor==JOptionPane.OK_OPTION){
            KartonTabelaModel ktm = (KartonTabelaModel) tabelaKartoni.getModel();
            Karton k = ktm.vratiKarton(red);
            ServerskiOdgovor so = Kontroler.getInstanca().deaktivirajKarton(k);
            if(so.getResponseStatus()==ResponseStatus.ERROR){
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, so.getPoruka(),"Poruka",JOptionPane.INFORMATION_MESSAGE);
                pretraga();
            }
        }
        
    }//GEN-LAST:event_jButtonDeaktivirajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaKartonaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaKartonaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaKartonaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaKartonaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaKartonaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziKarton;
    private javax.swing.JButton jButtonDeaktiviraj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaKartoni;
    private javax.swing.JTextField txtImePrezimeLbo;
    // End of variables declaration//GEN-END:variables

    private void centriraj() {
        setLocationRelativeTo(null);
    }

    private void popuniTabelu() {
        KartonTabelaModel ktm = new KartonTabelaModel();
        tabelaKartoni.setModel(ktm);
        pretraga();
    }

    public void pretraga() {
       String vrednost = txtImePrezimeLbo.getText().trim();
       Karton karton = new Karton(null, vrednost, vrednost,null, vrednost, null, null, null, null, null, null, null);
       List<Karton> kartoni = Kontroler.getInstanca().vratiListuKartona(karton);
       KartonTabelaModel ktm = (KartonTabelaModel) tabelaKartoni.getModel();
       ktm.setKartoni(kartoni);
    }

    private void postaviDugmice() {
        if(Kontroler.getInstanca().getUlogovani() instanceof Lekar){
           jButtonDeaktiviraj.setVisible(false);
        }
    }
}
