/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import domen.MedicinskaSestra;
import forme.kartoni.DodavanjeKartonaForma;
import forme.kartoni.PretragaKartonaForma;
import forme.pregledi.UnosPregledaForma;
import forme.zakazanipregledi.PretragaZakazanihPregledaForma;
import forme.zakazanipregledi.ZakazivanjePregledaForma;
import java.awt.Color;
import kontroler.Kontroler;

/**
 *
 * @author Danilo
 */
public class GlavnaKlijentskaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaKlijentskaForma
     */
    public GlavnaKlijentskaForma() {
        initComponents();
        centriraj();
        postaviNepromenljivostDimenzija();
        postaviNaslov();
        popuniFormu();
        postaviUlogovanogKorisnika();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuKartoni = new javax.swing.JMenu();
        jMenuItemDodajNoviKarton = new javax.swing.JMenuItem();
        jMenuItemPretraziKartone = new javax.swing.JMenuItem();
        jMenuPregledi = new javax.swing.JMenu();
        jMenuItemUnesiNoviPregled = new javax.swing.JMenuItem();
        jMenuItemZakaziPregled = new javax.swing.JMenuItem();
        jMenuItemPretraziZakazanePreglede = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/doktori.jpg"))); // NOI18N

        lblUlogovani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUlogovani.setText("jLabel2");

        jMenuKartoni.setText("Kartoni");

        jMenuItemDodajNoviKarton.setText("Dodaj novi karton");
        jMenuItemDodajNoviKarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajNoviKartonActionPerformed(evt);
            }
        });
        jMenuKartoni.add(jMenuItemDodajNoviKarton);

        jMenuItemPretraziKartone.setText("Pretraži kartone");
        jMenuItemPretraziKartone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziKartoneActionPerformed(evt);
            }
        });
        jMenuKartoni.add(jMenuItemPretraziKartone);

        jMenuBar1.add(jMenuKartoni);

        jMenuPregledi.setText("Pregledi");

        jMenuItemUnesiNoviPregled.setText("Unesi novi pregled");
        jMenuItemUnesiNoviPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnesiNoviPregledActionPerformed(evt);
            }
        });
        jMenuPregledi.add(jMenuItemUnesiNoviPregled);

        jMenuItemZakaziPregled.setText("Zakaži pregled");
        jMenuItemZakaziPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZakaziPregledActionPerformed(evt);
            }
        });
        jMenuPregledi.add(jMenuItemZakaziPregled);

        jMenuItemPretraziZakazanePreglede.setText("Pretraži zakazane preglede ");
        jMenuItemPretraziZakazanePreglede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziZakazanePregledeActionPerformed(evt);
            }
        });
        jMenuPregledi.add(jMenuItemPretraziZakazanePreglede);

        jMenuBar1.add(jMenuPregledi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUlogovani, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUlogovani)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDodajNoviKartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajNoviKartonActionPerformed
        DodavanjeKartonaForma dodaj = new DodavanjeKartonaForma(this, true, FormMode.FORM_ADD, null);
        dodaj.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajNoviKartonActionPerformed

    private void jMenuItemUnesiNoviPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnesiNoviPregledActionPerformed
        UnosPregledaForma upf = new UnosPregledaForma(this, true);
        upf.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnesiNoviPregledActionPerformed

    private void jMenuItemZakaziPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZakaziPregledActionPerformed
        ZakazivanjePregledaForma zpf = new ZakazivanjePregledaForma(this, true, FormMode.FORM_ADD,null);
        zpf.setVisible(true);
    }//GEN-LAST:event_jMenuItemZakaziPregledActionPerformed

    private void jMenuItemPretraziZakazanePregledeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziZakazanePregledeActionPerformed
        PretragaZakazanihPregledaForma pzf = new PretragaZakazanihPregledaForma();
        pzf.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretraziZakazanePregledeActionPerformed

    private void jMenuItemPretraziKartoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziKartoneActionPerformed
        PretragaKartonaForma pkf = new PretragaKartonaForma();
        pkf.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretraziKartoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaKlijentskaForma().setVisible(true);
            }
        });
    }

    private void centriraj() {
        setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDodajNoviKarton;
    private javax.swing.JMenuItem jMenuItemPretraziKartone;
    private javax.swing.JMenuItem jMenuItemPretraziZakazanePreglede;
    private javax.swing.JMenuItem jMenuItemUnesiNoviPregled;
    private javax.swing.JMenuItem jMenuItemZakaziPregled;
    private javax.swing.JMenu jMenuKartoni;
    private javax.swing.JMenu jMenuPregledi;
    private javax.swing.JLabel lblUlogovani;
    // End of variables declaration//GEN-END:variables

    

    private void popuniFormu() {
        Korisnik k = Kontroler.getInstanca().getUlogovani();
        if(k instanceof MedicinskaSestra){
            jMenuItemUnesiNoviPregled.setVisible(false);
        }
        else{
            jMenuItemDodajNoviKarton.setVisible(false);
            jMenuItemZakaziPregled.setVisible(false);
        }
    }

    private void postaviNaslov() {
        setTitle("Dobrodošli, "+Kontroler.getInstanca().getUlogovani());
    }

    private void postaviNepromenljivostDimenzija() {
        setResizable(false);
    }

    private void postaviUlogovanogKorisnika() {
        lblUlogovani.setText("Ulogovani korisnik: "+Kontroler.getInstanca().getUlogovani());
        
    }
}
