/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.pregledi;

import domen.Lek;
import domen.MernaJedinica;
import domen.Recept;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableColumn;
import modeli.LekTabelaModel;

/**
 *
 * @author Danilo
 */
public class DodavanjeRecepataForma extends javax.swing.JDialog {
    private SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
    private UnosPregledaForma upf;
    private List<Lek> lekovi;
    private Lek lek;

    /**
     * Creates new form DodavanjeRecepataForma
     */
    public DodavanjeRecepataForma(java.awt.Frame parent, boolean modal, List<Lek> lekovi, UnosPregledaForma upf) {
        super(parent, modal);
        initComponents();
        //centriraj();
        this.lekovi = lekovi;
        this.upf=upf;
        postaviNepromenljivostDimenzija();
        ograniciSpinner();
        popuniListuMernihJedinica();
        srediTabelu();
        srediKolone();
        srediPoljaZaIzabraniLek();
        postaviDatum();
        srediRBHitno();
        srediRBNeZamenjuj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDatumPropisivanja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbHitnoDa = new javax.swing.JRadioButton();
        rbHitnoNe = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbNeZamenjujDa = new javax.swing.JRadioButton();
        rbNeZamenjujNe = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDoza = new javax.swing.JTextField();
        spinnerKolicina = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMernihJedinica = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaNapomena = new javax.swing.JTextArea();
        txtPretragaLeka = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaLekovi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtJKL = new javax.swing.JTextField();
        txtATC = new javax.swing.JTextField();
        txtZasticenoIme = new javax.swing.JTextField();
        txtFO = new javax.swing.JTextField();
        btnDodajRecept = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj recept");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodavanje recepta"));

        jLabel1.setText("Pretraži lek po JKL ili delu imena:");

        jLabel2.setText("Datum propisivanja:");

        jLabel3.setText("Hitno:");

        rbHitnoDa.setText("Da");

        rbHitnoNe.setText("Ne");
        rbHitnoNe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHitnoNeActionPerformed(evt);
            }
        });

        jLabel4.setText("Ne zamenjuj:");

        rbNeZamenjujDa.setText("Da");

        rbNeZamenjujNe.setText("Ne");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Doziranje"));

        jLabel5.setText("Dati ");

        jLabel6.setText("(dnevno) x ");

        listaMernihJedinica.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaMernihJedinica);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDoza, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(txtDoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinnerKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Napomena:");

        txtAreaNapomena.setColumns(20);
        txtAreaNapomena.setRows(5);
        jScrollPane2.setViewportView(txtAreaNapomena);

        txtPretragaLeka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaLekaKeyReleased(evt);
            }
        });

        tabelaLekovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaLekovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLekoviMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaLekovi);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Izabrani lek"));

        jLabel8.setText("JKL:");

        jLabel9.setText("ATC:");

        jLabel10.setText("Zaštićeno ime leka:");

        jLabel11.setText("FO:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtATC)
                    .addComponent(txtZasticenoIme)
                    .addComponent(txtFO, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(txtJKL))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtJKL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtATC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtZasticenoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretragaLeka))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatumPropisivanja)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbNeZamenjujDa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbNeZamenjujNe))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbHitnoDa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbHitnoNe)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretragaLeka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatumPropisivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbHitnoDa)
                    .addComponent(rbHitnoNe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNeZamenjujDa)
                    .addComponent(rbNeZamenjujNe)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btnDodajRecept.setText("Dodaj recept");
        btnDodajRecept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajReceptActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodajRecept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOdustani)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajRecept)
                    .addComponent(btnOdustani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbHitnoNeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHitnoNeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHitnoNeActionPerformed

    private void tabelaLekoviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLekoviMouseClicked
        int red = tabelaLekovi.getSelectedRow();
        if(red>=0){
            LekTabelaModel ltm = (LekTabelaModel) tabelaLekovi.getModel();
            lek = ltm.vratiLek(red);
            txtATC.setText(lek.getAtc());
            txtFO.setText(lek.getFarmaceutskiOblik());
            txtJKL.setText(lek.getJkl());
            txtZasticenoIme.setText(lek.getZasticenoImeLeka());
            txtDoza.setText("1.0");
            txtDoza.grabFocus();
            txtDoza.setSelectionStart(0);
            TableColumn tc = tabelaLekovi.getColumnModel().getColumn(0);
            System.out.println("Duzina: "+tc.getPreferredWidth());
        }
    }//GEN-LAST:event_tabelaLekoviMouseClicked

    private void txtPretragaLekaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaLekaKeyReleased
        String vrednost=txtPretragaLeka.getText().trim().toUpperCase();
        pretragaUOperativnojMemoriji(vrednost);
    }//GEN-LAST:event_txtPretragaLekaKeyReleased

    private void btnDodajReceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajReceptActionPerformed
        if(lek==null){
            JOptionPane.showMessageDialog(null, "Morate izabrati lek!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean hitno=false;
        if(rbHitnoDa.isSelected()){
            hitno=true;
        }
        boolean neZamenjuj=false;
        if(rbNeZamenjujDa.isSelected()){
            neZamenjuj=true;
        }
        String napomena = txtAreaNapomena.getText();
        int kolicina = Integer.parseInt(spinnerKolicina.getModel().getValue().toString());
        double doza=0;
        try {
            doza = Double.parseDouble(txtDoza.getText());
        } catch (NumberFormatException numberFormatException) {
            numberFormatException.printStackTrace();
            JOptionPane.showMessageDialog(null, "Niste uneli dozu u odgovarajućem formatu!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        MernaJedinica mernaJedinica = (MernaJedinica) listaMernihJedinica.getSelectedValue();
        if(lek.getDdd()!=0){
            if(mernaJedinica==null){
                JOptionPane.showMessageDialog(null, "Niste izabrali jedinicu za doziranje!","Greška",JOptionPane.ERROR_MESSAGE);
                return;
             }
            if(!lek.getJedinicaZaDDD().equals(String.valueOf(mernaJedinica))){
                JOptionPane.showMessageDialog(null, "Jedinica za DDD leka nije ista kao jedinica koju ste izabrali!");
                return;
            }
            if(lek.getDdd()<doza*kolicina){
                JOptionPane.showMessageDialog(null, "Ukupna dnevna doza na receptu je veća od definisane dnevne doze leka "+lek+"!","Greška",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        Recept recept = new Recept(new Long(-1), new Date(), hitno, neZamenjuj, kolicina, doza, mernaJedinica, napomena, lek, null);
        upf.dodajRecept(recept);
        JOptionPane.showMessageDialog(null, "Uspešno dodat recept!", "Uspešno dodato", JOptionPane.INFORMATION_MESSAGE);
        System.out.println("Nesto");
        
    }//GEN-LAST:event_btnDodajReceptActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajRecept;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaMernihJedinica;
    private javax.swing.JRadioButton rbHitnoDa;
    private javax.swing.JRadioButton rbHitnoNe;
    private javax.swing.JRadioButton rbNeZamenjujDa;
    private javax.swing.JRadioButton rbNeZamenjujNe;
    private javax.swing.JSpinner spinnerKolicina;
    private javax.swing.JTable tabelaLekovi;
    private javax.swing.JTextField txtATC;
    private javax.swing.JTextArea txtAreaNapomena;
    private javax.swing.JTextField txtDatumPropisivanja;
    private javax.swing.JTextField txtDoza;
    private javax.swing.JTextField txtFO;
    private javax.swing.JTextField txtJKL;
    private javax.swing.JTextField txtPretragaLeka;
    private javax.swing.JTextField txtZasticenoIme;
    // End of variables declaration//GEN-END:variables

    private void centriraj() {
        setLocationRelativeTo(null);
    }

    private void postaviNepromenljivostDimenzija() {
        setResizable(false);
    }

    private void popuniListuMernihJedinica() {
        DefaultListModel<MernaJedinica> model = new DefaultListModel<>();
        listaMernihJedinica.setModel(model);
        
        model.addElement(MernaJedinica.gr);
        model.addElement(MernaJedinica.kom);
        model.addElement(MernaJedinica.lit);
        model.addElement(MernaJedinica.mg);
        model.addElement(MernaJedinica.cm);
        model.addElement(MernaJedinica.mcg);
        model.addElement(MernaJedinica.ij);
        model.addElement(MernaJedinica.Udah);
        model.addElement(MernaJedinica.Mazanje);
        
    }

    private void srediTabelu() {
        LekTabelaModel ltm = new LekTabelaModel();
        ltm.setLekovi(lekovi);
        tabelaLekovi.setModel(ltm);
    }

    private void srediPoljaZaIzabraniLek() {
        txtATC.setEditable(false);
        txtFO.setEditable(false);
        txtJKL.setEditable(false);
        txtZasticenoIme.setEditable(false);
    }

    private void postaviDatum() {
        Date datum = new Date();
        txtDatumPropisivanja.setText(sdf.format(datum));
        txtDatumPropisivanja.setEditable(false);
    }

    private void pretragaUOperativnojMemoriji(String vrednost) {
        LekTabelaModel ltm = (LekTabelaModel) tabelaLekovi.getModel();
        if(vrednost.isEmpty()){
            ltm.setLekovi(lekovi);
        }
        else{
            List<Lek> filtrirani = new ArrayList<>();
            for (Lek l : lekovi) {
                if(l.getJkl().contains(vrednost) || l.getZasticenoImeLeka().contains(vrednost)){
                    filtrirani.add(l);
                }
            }
            ltm.setLekovi(filtrirani);
        }
    }

    private void ograniciSpinner() {
        SpinnerNumberModel snm = new SpinnerNumberModel(1,1,10,1);
        spinnerKolicina.setModel(snm);
    }

    private void srediKolone() {
        //tabelaLekovi.setAutoResizeMode(tabelaLekovi.AUTO_RESIZE_OFF);
        TableColumn jkl = tabelaLekovi.getColumnModel().getColumn(0);
        jkl.setPreferredWidth(10);
        TableColumn atc = tabelaLekovi.getColumnModel().getColumn(1);
        atc.setPreferredWidth(10);
        TableColumn zasticenoIme = tabelaLekovi.getColumnModel().getColumn(2);
        zasticenoIme.setPreferredWidth(90);
        TableColumn pakovanjeIJacina = tabelaLekovi.getColumnModel().getColumn(3);
        pakovanjeIJacina.setPreferredWidth(190);
        
    }

    private void srediRBHitno() {
        ButtonGroup group = new ButtonGroup();
        group.add(rbHitnoDa);
        group.add(rbHitnoNe);
        rbHitnoDa.setSelected(true);
        
    }

    private void srediRBNeZamenjuj() {
        ButtonGroup group = new ButtonGroup();
        group.add(rbNeZamenjujDa);
        group.add(rbNeZamenjujNe);
        rbNeZamenjujDa.setSelected(true);
    }
}
